name: Cleanup

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  container-images:
    runs-on: docker
    name: Container-Images
    steps:
      - uses: https://github.com/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Cleanup
        uses: ./
        with:
          instance: https://codeberg.org
          username: jvllmr
          password: ${{ secrets.PUBLISH_TOKEN }}
          package: ^forgejo-pkg-cleanup(?:-cache)?$
          packageType: container
          owner: jvllmr
          keepVersions: ^(?:(?:v)?(?:\d+)(?:\.(\d+))?(?:\.(\d+))?(?:[a|b]\d+)?)?(?:main)?$
          retention: 6h
