name: Test docker workflow

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Who to greet in the log
        required: true
        default: "World"
        type: string

jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-latest

    steps:
      - name: Print to Log
        id: print-to-log
        uses: https://github.com/actions/container-prebuilt-action@c9bd8fbb1ccc880197428fd44480e04576fa4c5e # v0.2.0
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
